<a href="https://colab.research.google.com/github/JoseSergio414/Fontes_dados/blob/main/Dadosfinal3sprint_exp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dados importação e exportação (3° Etapa todos em único arquivo)

In [1]:
import pandas as pd

In [2]:
data = {'coluna_1':[1.5,2.0,1.7,2.2,1.9],
        'coluna_2':[10.0,12.0,11.5,13.0,11.0],
        'coluna_3':[0,1,0,1,0],
        'coluna_4':[1,0,1,1,0],
        'coluna_5':[20.5,25.5,22.0,27.0,23.0]}

In [3]:
df = pd.DataFrame(data)

In [4]:
print(df)

   coluna_1  coluna_2  coluna_3  coluna_4  coluna_5
0       1.5      10.0         0         1      20.5
1       2.0      12.0         1         0      25.5
2       1.7      11.5         0         1      22.0
3       2.2      13.0         1         1      27.0
4       1.9      11.0         0         0      23.0

In [5]:
from google.colab import drive

In [6]:
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
origem = '/content/drive/MyDrive/Data/COMEXSTAT/'

In [8]:
arquivo_1 = origem + 'exp.csv'
arquivo_2 = origem + 'imp.csv'

In [9]:
exp = pd.read_csv(arquivo_1, low_memory=False, sep=',', encoding='UTF-8', quotechar='"')
imp = pd.read_csv(arquivo_2, low_memory=False, sep=',', encoding='UTF-8', quotechar='"')

In [28]:
dado_final_pivot.to_csv(origem + 'dado_final_pivot.csv', index=False)
print('DataFrame salvo com sucesso em dado_final_pivot.csv')

DataFrame salvo com sucesso em dado_final_pivot.csv

In [26]:
dado_final_pivot['Trade Balance'] = dado_final_pivot['Exportation Value'] - dado_final_pivot['Importation Value']
dado_final_pivot.rename(columns={'Trade Balance': 'Saldo da balança comercial'}, inplace=True)

In [27]:
display(dado_final_pivot.head())

,CO_ANO_,CO_MES_,SH4_,CO_PAIS_,SG_UF_MUN_,CO_MUN_,CO_SH4_,NO_SH4_POR_,NO_PAIS_,CO_MUN_GEO_,NO_MUN_MIN_,Exportation KG,Importation KG,Exportation Value,Importation Value,Saldo da balança comercial
0,2021,1,101,23,SP,3428502,101,"Cavalos, asininos e muares, vivos",Alemanha,3428502,Mairiporã,0.0,700.0,0.0,40144.0,-40144.0
1,2021,1,101,23,SP,3447304,101,"Cavalos, asininos e muares, vivos",Alemanha,3447304,Santana de Parnaíba,0.0,500.0,0.0,36324.0,-36324.0
2,2021,1,101,63,PR,4106902,101,"Cavalos, asininos e muares, vivos",Argentina,4106902,Curitiba,600.0,0.0,11375.0,0.0,11375.0
3,2021,1,101,63,RJ,3304557,101,"Cavalos, asininos e muares, vivos",Argentina,3304557,Rio de Janeiro,0.0,1500.0,0.0,13600.0,-13600.0
4,2021,1,101,63,RJ,3305802,101,"Cavalos, asininos e muares, vivos",Argentina,3305802,Teresópolis,0.0,2000.0,0.0,17000.0,-17000.0

In [24]:
index_cols = dado_final.columns.drop(['VL_FOB', 'KG_LIQUIDO', 'tipo_fluxo']).tolist()
dado_final_pivot = dado_final.pivot_table(index=index_cols,
                                          columns='tipo_fluxo',
                                          values=['VL_FOB', 'KG_LIQUIDO'],
                                          aggfunc='sum').fillna(0).reset_index()

# Flatten the MultiIndex columns
dado_final_pivot.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in dado_final_pivot.columns.values]

# Rename the new columns for clarity
dado_final_pivot.rename(columns={
    'VL_FOB_EXPORTAÇÃO': 'Exportation Value',
    'VL_FOB_IMPORTAÇÃO': 'Importation Value',
    'KG_LIQUIDO_EXPORTAÇÃO': 'Exportation KG',
    'KG_LIQUIDO_IMPORTAÇÃO': 'Importation KG'
}, inplace=True)

In [25]:
display(dado_final_pivot.head())

,CO_ANO_,CO_MES_,SH4_,CO_PAIS_,SG_UF_MUN_,CO_MUN_,CO_SH4_,NO_SH4_POR_,NO_PAIS_,CO_MUN_GEO_,NO_MUN_MIN_,Exportation KG,Importation KG,Exportation Value,Importation Value
0,2021,1,101,23,SP,3428502,101,"Cavalos, asininos e muares, vivos",Alemanha,3428502,Mairiporã,0.0,700.0,0.0,40144.0
1,2021,1,101,23,SP,3447304,101,"Cavalos, asininos e muares, vivos",Alemanha,3447304,Santana de Parnaíba,0.0,500.0,0.0,36324.0
2,2021,1,101,63,PR,4106902,101,"Cavalos, asininos e muares, vivos",Argentina,4106902,Curitiba,600.0,0.0,11375.0,0.0
3,2021,1,101,63,RJ,3304557,101,"Cavalos, asininos e muares, vivos",Argentina,3304557,Rio de Janeiro,0.0,1500.0,0.0,13600.0
4,2021,1,101,63,RJ,3305802,101,"Cavalos, asininos e muares, vivos",Argentina,3305802,Teresópolis,0.0,2000.0,0.0,17000.0

In [10]:
exp['tipo_fluxo'] = 'EXPORTAÇÃO'
imp['tipo_fluxo'] = 'IMPORTAÇÃO'

In [11]:
dado_final=pd.concat([exp,imp,], ignore_index=True)
dado_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13159539 entries, 0 to 13159538
Data columns (total 14 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   SH4         int64
 3   CO_PAIS     int64
 4   SG_UF_MUN   object
 5   CO_MUN      int64
 6   KG_LIQUIDO  int64
 7   VL_FOB      int64
 8   CO_SH4      int64
 9   NO_SH4_POR  object
 10  NO_PAIS     object
 11  CO_MUN_GEO  int64
 12  NO_MUN_MIN  object
 13  tipo_fluxo  object
dtypes: int64(9), object(5)
memory usage: 1.4+ GB

In [12]:
dado_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13159539 entries, 0 to 13159538
Data columns (total 14 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   SH4         int64
 3   CO_PAIS     int64
 4   SG_UF_MUN   object
 5   CO_MUN      int64
 6   KG_LIQUIDO  int64
 7   VL_FOB      int64
 8   CO_SH4      int64
 9   NO_SH4_POR  object
 10  NO_PAIS     object
 11  CO_MUN_GEO  int64
 12  NO_MUN_MIN  object
 13  tipo_fluxo  object
dtypes: int64(9), object(5)
memory usage: 1.4+ GB

In [13]:
dado_final.head(5)

,CO_ANO,CO_MES,SH4,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,NO_PAIS,CO_MUN_GEO,NO_MUN_MIN,tipo_fluxo
0,2021,3,3305,493,SP,3434401,966,7788,3305,Preparações capilares,México,3434401,Osasco,EXPORTAÇÃO
1,2021,7,8419,386,SP,3409502,1,1544,8419,"Aparelhos e dispositivos, mesmo aquecidos elec...",Itália,3409502,Campinas,EXPORTAÇÃO
2,2021,12,8511,63,PR,4106902,73,907,8511,Aparelhos e dispositivos elétricos de ignição ...,Argentina,4106902,Curitiba,EXPORTAÇÃO
3,2021,7,6204,586,SC,4202909,75,3942,6204,"Fatos de saia-casaco, conjuntos, casacos, vest...",Paraguai,4202909,Brusque,EXPORTAÇÃO
4,2021,8,8708,63,SP,3440002,6949,29604,8708,Partes e acessórios dos veículos automóveis da...,Argentina,3440002,Pompéia,EXPORTAÇÃO

In [14]:
dado_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13159539 entries, 0 to 13159538
Data columns (total 14 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   SH4         int64
 3   CO_PAIS     int64
 4   SG_UF_MUN   object
 5   CO_MUN      int64
 6   KG_LIQUIDO  int64
 7   VL_FOB      int64
 8   CO_SH4      int64
 9   NO_SH4_POR  object
 10  NO_PAIS     object
 11  CO_MUN_GEO  int64
 12  NO_MUN_MIN  object
 13  tipo_fluxo  object
dtypes: int64(9), object(5)
memory usage: 1.4+ GB

In [15]:
dado_final.drop_duplicates(inplace=True)
print("Duplicate rows removed.")

Duplicate rows removed.

Now, filter the DataFrame based on your chosen SH4 codes. Please provide the list of SH4 codes you want to keep in the `selected_sh4_codes` variable.

In [16]:
dado_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13159539 entries, 0 to 13159538
Data columns (total 14 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   SH4         int64
 3   CO_PAIS     int64
 4   SG_UF_MUN   object
 5   CO_MUN      int64
 6   KG_LIQUIDO  int64
 7   VL_FOB      int64
 8   CO_SH4      int64
 9   NO_SH4_POR  object
 10  NO_PAIS     object
 11  CO_MUN_GEO  int64
 12  NO_MUN_MIN  object
 13  tipo_fluxo  object
dtypes: int64(9), object(5)
memory usage: 1.4+ GB

In [17]:
dado_final.head(5)

,CO_ANO,CO_MES,SH4,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,NO_PAIS,CO_MUN_GEO,NO_MUN_MIN,tipo_fluxo
0,2021,3,3305,493,SP,3434401,966,7788,3305,Preparações capilares,México,3434401,Osasco,EXPORTAÇÃO
1,2021,7,8419,386,SP,3409502,1,1544,8419,"Aparelhos e dispositivos, mesmo aquecidos elec...",Itália,3409502,Campinas,EXPORTAÇÃO
2,2021,12,8511,63,PR,4106902,73,907,8511,Aparelhos e dispositivos elétricos de ignição ...,Argentina,4106902,Curitiba,EXPORTAÇÃO
3,2021,7,6204,586,SC,4202909,75,3942,6204,"Fatos de saia-casaco, conjuntos, casacos, vest...",Paraguai,4202909,Brusque,EXPORTAÇÃO
4,2021,8,8708,63,SP,3440002,6949,29604,8708,Partes e acessórios dos veículos automóveis da...,Argentina,3440002,Pompéia,EXPORTAÇÃO

In [18]:
dado_final.tail(5)

,CO_ANO,CO_MES,SH4,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,NO_PAIS,CO_MUN_GEO,NO_MUN_MIN,tipo_fluxo
13159534,2025,4,8512,355,SP,3426902,0,29,8512,Aparelhos elétricos de iluminação ou de sinali...,Hungria,3426902,Limeira,IMPORTAÇÃO
13159535,2025,9,8471,23,RS,4304804,3,530,8471,Máquinas automáticas para processamento de dad...,Alemanha,4304804,Carlos Barbosa,IMPORTAÇÃO
13159536,2025,5,3904,275,MG,3133006,41376,227704,3904,Polímeros de cloreto de vinilo ou de outras ol...,França,3133006,Itamonte,IMPORTAÇÃO
13159537,2025,2,9010,160,SP,3441406,12150,10892,9010,Aparelhos e material dos tipos usados nos labo...,China,3441406,Presidente Prudente,IMPORTAÇÃO
13159538,2025,4,3920,399,SC,4208203,3742,17358,3920,"Outras chapas, folhas, películas, tiras e lâmi...",Japão,4208203,Itajaí,IMPORTAÇÃO

In [19]:
coluna = 'NO_PAIS'
cp = dado_final[coluna].value_counts().sort_values(ascending=False)
print(f'total de operações {coluna}:')
print(cp)

total de operações NO_PAIS:
NO_PAIS
China                          1613482
Estados Unidos                 1225896
Alemanha                        786340
Itália                          538278
Argentina                       450500
                                ...
Bouvet, Ilha                        12
Svalbard e Jan Mayen                11
Saara Ocidental                      8
São Pedro e Miquelon                 4
Organizações Internacionais          4
Name: count, Length: 252, dtype: int64

In [20]:
print(dado_final.columns)

Index(['CO_ANO', 'CO_MES', 'SH4', 'CO_PAIS', 'SG_UF_MUN', 'CO_MUN',
       'KG_LIQUIDO', 'VL_FOB', 'CO_SH4', 'NO_SH4_POR', 'NO_PAIS', 'CO_MUN_GEO',
       'NO_MUN_MIN', 'tipo_fluxo'],
      dtype='object')

In [21]:
dado_final.to_csv(origem+'dado_final.csv',index=False)

# Task
Transform the `dado_final` DataFrame by pivoting it to create 'Exportation Value' and 'Importation Value' columns from the `VL_FOB` column, based on the `tipo_fluxo` column. Fill any resulting NaN values with 0 and reset the index.

## Transform DataFrame

### Subtask:
Pivot the `dado_final` DataFrame to create separate columns for 'Exportation Value' and 'Importation Value' from the `VL_FOB` column, based on the `tipo_fluxo` column. Then, fill any NaN values with 0 and reset the index.

## Summary:

### Data Analysis Key Findings
*   The `dado_final` DataFrame was successfully transformed by pivoting the `VL_FOB` column. This operation created two new distinct columns: 'Exportation Value' and 'Importation Value', with values derived from `VL_FOB` based on the `tipo_fluxo` (flow type) column.
*   All missing values (NaN) that resulted from the pivoting operation were uniformly replaced with zeros.
*   The DataFrame's index was reset, providing a clean, default integer index for the transformed data.

### Insights or Next Steps
*   The restructured DataFrame, with separate columns for export and import values, is now prepared for direct comparison and analysis of trade balances or trends.
*   The next step could involve aggregating these values by different dimensions (e.g., year, product, country) or visualizing the export and import values over time.